### PR TITLE
modified test_wait_timer.py to allow faster testing without sleeps

### PR DESCRIPTION
**Pull request by nconde**
Signed-off-by: nconde <naissa.conde@intel.com>

### CODE REVIEW

**Comment by jjason** [comment]
Please clean up first commit by removing commented out code and prints, then rebase and re-push PR.

**Comment by nconde** [comment]
Those were fixed in the second commit

**Comment by jjason** [comment]
@nconde Instead of being removed in the second commit, I believe that the group "standard" is to not allow them in the first commit.

**Comment by nconde** [comment]
@jjason fixed

**Pull request merged**
