### PR TITLE
Remove the duplicate definite article

### PR DESCRIPTION
**Pull request by feihujiang**
Signed-off-by: feihujiang <jiangfeihu@huawei.com>

### CODE REVIEW

**Comment by boydjohnson** [comment]
Thanks @feihujiang, This will be merged in within the hour. Thanks for the good work.

**Comment by boydjohnson** [comment]
Hi @feihujiang Just to let you know I won't be able to merge it until tomorrow.

**Comment by feihujiang** [comment]
@boydjohnson I saw the sentence "Before contributing any code, note that you will be asked to sign-off on the [Developer Certificate of Origin](http://developercertificate.org/)" in [CONTRIBUTING.md](https://github.com/hyperledger/sawtooth-core/blob/master/CONTRIBUTING.md).
 Where should I sign-off on the Developer Certificate of Origin?  Or just using git commit -s/--signoff is OK?

**Comment by boydjohnson** [comment]
I don't know about that. 

The commit was merged in, but I did something wrong on merging it that the commit hash was changed and so your PR wasn't closed by the commit being merged in.

You can check out https://github.com/hyperledger/sawtooth-core/commit/e7a57efb1c52b0b5a460f0f940b55a7fb3bed59a to see your commit in the codebase.

This PR will have to be closed manually.

**Comment by feihujiang** [comment]
OK， close this PR manually.

**Pull request closed without merging**
