### PR TITLE
Add Delete State functionality in java sdk

### PR DESCRIPTION
**Pull request by dharamsh**
This method will allow to delete the state
using state address in java sdk

Signed-off-by: Dharam Raj Sharma <dharam.rajx.sharma@intel.com>

### CODE REVIEW

**Comment by peterschwarz** [comment]
@Ram-srini On your second point, the list of addresses returned are all of the addresses that have been deleted.  If an address include in the request is not in the response, it most likely did not exist.

As far as validity goes, that result in an Authorization Error (i.e. the user is trying to modify/access an unauthorized address). There is no status specifically for malformed addresses.

This PR is handling both correctly, as far as the protobuf messages are concerned.

**Comment by aludvik** [comment]
This PR will be deprecated by https://github.com/hyperledger/sawtooth-core/pull/1734 and should be made against the Java SDK repo when it is ready: https://github.com/hyperledger/sawtooth-sdk-java

**Comment by boydjohnson** [comment]
@dharamsh The java sdk has been moved into a separate repo: http://github.com/hyperledger/sawtooth-sdk-java. This Pr should be closed and made against that repo.

**Comment by vaporos** [comment]
Closing due to Java SDK now existing in the other repository.

**Pull request closed without merging**
