### PR TITLE
Add tests of valid and invalid signature

### PR DESCRIPTION
**Pull request by feihujiang**
Signed-off-by: feihujiang <jiangfeihu@huawei.com>

### CODE REVIEW

**Comment by vaporos** [comment]
This PR needs to be rebased.

**Comment by feihujiang** [comment]
@vaporos I rebased this PR, please take a look.

**Comment by feihujiang** [comment]
@vaporos I just rebased this PR. Could you please review and merge this PR?

**Comment by vaporos** [comment]
This change has been accepted and cherry-picked to the 0-7 branch.  Changes to "legacy code" that is not part of the 0.8 validator are not being merged into master, so closing this PR against master.

**Pull request closed without merging**
