### PR TITLE
Fixing build_all for cxx code relocation

### PR DESCRIPTION
**Pull request by rranjan3**
Cleaning up build_all to remove cxx build functions
and module list.

Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>

### CODE REVIEW

**Comment by rranjan3** [comment]
Probable miss in [PR-1732](https://github.com/hyperledger/sawtooth-core/pull/1732). Was causing build_all to fail.

**Comment by peterschwarz** [comment]
Could you please amend your commit message to follow more of the guidelines found in this blog post? 

I would suggest changing the tense in the Summary. More like:

> Remove cxx from build_all

**Comment by rranjan3** [comment]
Thanks Peter. I have updated it. Which blog post were you pointing to ?

**Comment by peterschwarz** [comment]
Sorry, badly formatted my comment: https://chris.beams.io/posts/git-commit

**Comment by rbuysse** [comment]
bin/build_all is removed entirely in #1729.

**Comment by rranjan3** [comment]
Thanks @rbuysse for pointing me to this PR. In that case I should close this PR and wait for 1729 to be merged.

**Pull request closed without merging**
