### PR TITLE
1.0.2.backports

### PR DESCRIPTION
**Pull request by peterschwarz**
This in includes the following PRS:

PoET Fixes:
#1288 
#1411 

Bug Fixes (and necessary refactorings):
#1324 
#1340 
#1344 
#1386
#1400 
#1404 
#1413 
#1416 
#1430 
#1434 
#1442 
#1445 
#1453 
#1461 

Doc Changes:
#1389 
#1390 
#1391 
#1394 
#1395 

Non-breaking changes:
#1376

### CODE REVIEW

**Comment by grkvlt** [comment]
Can we add #1463 to this as well, please?

**Comment by peterschwarz** [comment]
Added #1463

**Comment by grkvlt** [comment]
is the build failure because of #1463 or is it unrelated? it looks like a timeout problem:
> `ERROR:__main__:Command '['docker-compose', '-p', 'f4552690ceca87a9cc387dc180113b2a2e47efc4376594306a803e7fcac64828', '-f', './sdk/examples/xo_python/tests/test_tp_xo_java.yaml', 'up', '--abort-on-container-exit']' timed out after 599.999541759491 seconds`

**Comment by dcmiddle** [comment]
@chenette can you please look thru the build artifacts and make sure you got what you were expecting from the doc backports

**Pull request merged**
