### PR TITLE
BACKPORT: Add client_max_size to rest api config

### PR DESCRIPTION
**Pull request by peterschwarz**
Before the REST API defaulted to only allowing a
request body size of 1MB. Now the size limit can be
configured with the config file or using the command
line. If there is not a size configured there will be
no limit on the request body size.

Signed-off-by: Andrea Gunderson <agunde@bitwise.io>

### CODE REVIEW

**Comment by dcmiddle** [comment]
Can the limitless default cause a denial of service for that rest service?

**Comment by dcmiddle** [comment]
@agunde406 can you give context on the default ^

**Comment by agunde406** [comment]
The default was chosen because the rest api has been written to be very permissive. For example, there is no authorization scheme or CORS handling. From talking with @delventhalz, the rest-api should not be exposed without modification (such as setting a response body limit). For example, for production, it should be put behind a proxy.

**Comment by dcmiddle** [comment]
Thanks for the context @agunde406. The deployment model should indeed be that each participating company decides whether or not to _internally_ host a REST API instance. That implies a security model where certain attacks are out of scope, but it should still be resilient to bad requests from 'internal' users.

**Comment by peterschwarz** [comment]
This now depends on #1580

**Pull request merged**
