### PR TITLE
Improve sawadm package name and metadata

### PR DESCRIPTION
**Pull request by KirillVusik**
Signed-off-by: Kirill Vusik <kirillvusik@coherentsolutions.com>

### CODE REVIEW

**Comment by rberg2** [comment]
Here is the package metadata after this change.
```dpkg-deb -I sawtooth-sawadm_1.3.1-dev2_amd64.deb
 new Debian package, version 2.0.
 size 451192 bytes: control archive=999 bytes.
     580 bytes,    13 lines      control              
     123 bytes,     2 lines      md5sums              
     900 bytes,    29 lines   *  postinst             #!/bin/bash
 Package: sawtooth-sawadm
 Version: 1.3.1-dev2
 Architecture: amd64
 Section: admin
 Priority: optional
 Standards-Version: 3.9.4
 Maintainer: sawtooth
 Installed-Size: 1317
 Depends: libsodium23 (>= 1.0.16), libssl1.1 (>= 1.1.0g), libpgm-5.2-0 (>= 5.2.122~dfsg), libzmq5 (>= 4.2.5), libstdc++6 (>= 8.3.0), libgcc1 (>= 1:8.3.0), libc6 (>= 2.27), libnorm1 (>= 1.5r6+dfsg1)
 Description: The sawadm command is used for Sawtooth administration tasks.
  The sawadm subcommands create validator keys during initial configuration and
  help create the genesis block when initializing a validator.
```

**Comment by jsmitchell** [comment]
> Here is the package metadata after this change.

In addition to the keygen and genesis functions, there are a variety of blockstore database administrative functions. The subcommands and options are described here: https://github.com/hyperledger/sawtooth-core/blob/master/adm/src/main.rs#L67

**Comment by chenette** [comment]
@jsmitchell The current documentation (the output of `sawadm --help`) shows only the `genesis` and `keygen` subcommands.  Should the other subcommands be added to the help output?  In a separate PR, of course.

**Comment by jsmitchell** [comment]
> @jsmitchell The current documentation (the output of `sawadm --help`) shows only the `genesis` and `keygen` subcommands. Should the other subcommands be added to the help output? In a separate PR, of course.

Yes

**Comment by KirillVusik** [comment]
@jsmitchell, @chenette  should I add additional info from https://github.com/hyperledger/sawtooth-core/blob/master/adm/src/main.rs#L67 to the extended-description field?

**Comment by KirillVusik** [comment]
Just in case I don't have a write access to merge

**Pull request merged**
