### PR TITLE
Add in missing imports

### PR DESCRIPTION
**Pull request by cclauss**
Added missing imports:
* import getpass
* from  base64 import b64encode

### CODE REVIEW

**Comment by dcmiddle** [comment]
@peterschwarz can you take a look at this? Looks like you added the code requiring the imports.

**Comment by peterschwarz** [comment]
Probably need to add these files to the pylint paths.

**Comment by cclauss** [comment]
These are standard library imports.  I would hope that if they are imported then pylint should be able to find them without further hinting.

**Comment by peterschwarz** [comment]
I don't mean the libraries imported, I'm referring to the portion of the
sawtooth source tree.  This sub path isn't part of the `run_lint` script

**Comment by cclauss** [comment]
Closed in favor of #987

**Pull request closed without merging**
