### PR TITLE
Supplychain State Delta Subscriber

### PR DESCRIPTION
**Pull request by peterschwarz**
This PR introduces a state delta subscriber for the supplychain family.

Note, this requires a Postgres Database setup with the tables specified in #714.  There may be some setup scripts that need to be added for testing.

### CODE REVIEW

**Comment by peterschwarz** [comment]
A future PR will be needed to create a docker container for this.

**Comment by peterschwarz** [comment]
Also will modify the cli to init the DB

**Comment by peterschwarz** [comment]
Updated to add a tool for initialize the database.

Usage:  
```
$ supplychain-sds init --database-user $MYUSER --database-password $MYPASSWORD
```

**Comment by peterschwarz** [comment]
## Testing

Start a validator instance and connect a supplychain transaction processor. 
Start Postgres instance:

```
$ docker run -e POSTGRES_USER=supplychain -e POSTGRES_PASSWORD=example -e POSTGRES_DB=supplychain --name postgres -p 5432:5432 -d postgres
```

Initialize the db:

```
$ supplychain-sds init --database-user supplychain --database-password example
```

Start the subscriber process:

```
$ ./bin/supplychain-sds -vv subscribe --database-user supplychain --database-password example
```

Submit transactions to the validator using the `supplychain` CLI tool.

* Verify that the subscriber process logs receiving events
* Verify that the tables are populated:
    Start psql
    ```
    $ docker run -it --rm --link postgres:postgres postgres psql -h postgres -U supplychain
    ```
    Query for agents (for example):
    ```
    supplychain=# select * from agent;
    ```

**Comment by agunde406** [comment]
Tested locally

**Comment by peterschwarz** [comment]
Added example config files.

**Comment by peterschwarz** [comment]
Docker containers will be the scope of a future PR, after #714 is merged.

**Pull request merged**
