### PR TITLE
clippy scan results fix.

### PR DESCRIPTION
**Pull request by mithunshashidhara**
clippy scan on validator showed many lint issues.
this PR contains fix for few of them.

Signed-off-by: mithunshashidhara <mithunx.shashidhara@intel.com>

### CODE REVIEW

**Comment by dcmiddle** [comment]
rework of https://github.com/hyperledger/sawtooth-core/pull/1747

**Comment by dcmiddle** [comment]
@aludvik is 📎 correct that these methods are unused?

**Comment by boydjohnson** [comment]
@dcmiddle https://github.com/hyperledger/sawtooth-core/blob/master/validator/sawtooth_validator/ffi.py#L65 `pylogger_init` ffi code that is called by python code.

**Comment by dcmiddle** [comment]
Thanks for trying to appease clippy @mithunshashidhara. Unfortunately it looks like these were false positives.
@TomBarnes fyi ^

**Pull request closed without merging**
