### PR TITLE
Delete the two files: network_configuration.rst and architecture_over…

### PR DESCRIPTION
**Pull request by Haridhakshini**
…view.rst

"Signed-off-by: Haridhakshini <s.a.haridhakshini@gmail.com>"

### CODE REVIEW

**Comment by dcmiddle** [comment]
@Haridhakshini  I think this file might need to be updated to remove the references to the deleted files
docs/source/sawtooth_developers_guide.rst

**Comment by dcmiddle** [comment]
@Haridhakshini thanks for editing the other file. Can you amend that commit to add the sign off?
commands will be something like 
```
git commit --amend -s

#force push the altered commit
git push <yourfork> <this-feature-branch> -f 
```

**Comment by Haridhakshini** [comment]
Dan, Thanks for finding about the reference file and letting me know. I just signed it off as well.

**Comment by jsmitchell** [comment]
These commits were merged in https://github.com/hyperledger/sawtooth-core/pull/324

**Pull request closed without merging**
