### PR TITLE
Missing library in subprocess manage type

### PR DESCRIPTION
**Pull request by ojalatodd**
The sys library was needed but missing.
Added import of sys.

Signed-off-by: Todd Ojala <todd@bitwise.io>

### CODE REVIEW

**Comment by ojalatodd** [comment]
Added manage to run_lint.
This causes multiple linting errors in docker and subprocess manage methods. 
Should I fix those as part of this PR, @peterschwarz ?

**Comment by ojalatodd** [comment]
I fixed the linting errors in the manage library modules as part of this PR.

**Comment by peterschwarz** [comment]
Rebase the "fix linting error" commit back into the original commit for this PR and we'll call it good.

**Comment by ojalatodd** [comment]
@peterschwarz I rebased. Should be good.

**Pull request merged**
