### PR TITLE
Add missing dependency to local shell dockerfile

### PR DESCRIPTION
**Pull request by rbuysse**
Signed-off-by: Ryan Beck-Buysse <rbuysse@bitwise.io>

### CODE REVIEW

**Comment by rbuysse** [comment]
Fixes the bug reported here: https://chat.hyperledger.org/channel/sawtooth?msg=E3LqqiGGvEMQrCZhs

**Comment by rberg2** [comment]
also: https://jira.hyperledger.org/browse/STL-1499

**Comment by danintel** [comment]
A silent change is to change the keys from the stable branch to nightly. Would this still work after release? Could we install both keys. Something like what I do:

`apt-key adv . . .--recv-keys 44FC67F19B2466EA 8AA7AF1F1091A5FD`

**Comment by rbuysse** [comment]
@danintel this change brings this development dockerfile in line with the rest in the repository. Previously it was only installing non-sawtooth (cbor, colorlog, toml, etc...) dependencies from the /ci repository, but now that the python-sdk has been moved to its own repo, we need to install it from the published artifact.

We want core developers always using nightly published artifacts from the other repos so we can discover breaking changes prior to releases.

**Pull request merged**
