### PR TITLE
Fix terminology: any batch signer -> any transaction signer

### PR DESCRIPTION
**Pull request by LiyanJin**
Signed-off-by: Hans Jin <hans_jin@126.com>

### CODE REVIEW

**Comment by LiyanJin** [comment]
It doesn't work for me even with s Signed-off-by in the commit

**Comment by arsulegai** [comment]
I know it's not good approach, but did you leave an empty line gap between commit message and the signed-off line, also please confirm that the email id is attached to the github account.

**Comment by dcmiddle** [comment]
Closing this PR in favor of #2295 which also has this commit.

**Comment by LiyanJin** [comment]
@arsulegai Thanks so much for your reminder. I will pay attention to it next time.

**Pull request closed without merging**
