### PR TITLE
Fix the bug of showing transaction info

### PR DESCRIPTION
**Pull request by feihujiang**
Use '''./bin/sawtooth transaction list''' command to show a few general fields of all transactions.
And Use '''./bin/sawtooth transaction list --type /EndpointRegistryTransaction''' to show a few general and specific fields of transactions.

@dcmiddle please review this PR.

### CODE REVIEW

**Comment by feihujiang** [comment]
@boydjohnson Could you please reivew this PR please? Thanks.

**Comment by boydjohnson** [comment]
Hi @feihujiang, I see that you didn't sign off on your commit. Can you edit the commit using "rebase -i" and then "git commit --amend --signoff". I will be back in the office on Monday, Nov 28th and will hopefully merge it in then.

**Comment by feihujiang** [comment]
@boydjohnson OK, thanks. I added the sign-off message.

**Comment by boydjohnson** [comment]
HI @feihujiang, I like the PR. Please rebase on current master. Our internal test system requires a directory structure that came later than your commit. Thanks.

**Comment by feihujiang** [comment]
@boydjohnson I rebased on the current master, please take a look.

**Pull request merged**
