### PR TITLE
Add unit tests for batch.py in cli module

### PR DESCRIPTION
**Pull request by adityasingh177**
The unit tests increase code coverage for cli module
code coverage increased as per nose2-3 report

Signed-off-by: aditya singh <adityasingh27@hotmail.com>

### CODE REVIEW

**Comment by rberg2** [comment]
Hello, I have added you to the whitelist what was preventing this PR from building and restarted the build. Thanks!

**Comment by adityasingh177** [comment]
Updated the changes accordingly.Please have a review @dcmiddle @askmish

**Comment by kulkarniamol** [comment]
Looks good.

**Comment by kulkarniamol** [comment]
Dan, I'm waiting for the end-to-end REST validation to catch up. Will likely pull this set of tests into that and delete this PR.

**Pull request closed without merging**
