### PR TITLE
corrected a typo in notes. Alway -> always

### PR DESCRIPTION
**Pull request by verasnt**
A simple typo correction in "Transactions and Batches" page.

### CODE REVIEW

**Comment by peterschwarz** [comment]
You need to have a signed-off commit.  If you could please do a `git commit -s --amend` and repush the branch, it should be good to go.

**Comment by aludvik** [comment]
I think we need to remove that merge commit and instead do a rebase.

**Comment by peterschwarz** [comment]
Looks like the Portuguese doc should be on a separate branch (though very cool that you're working on it!)

**Comment by peterschwarz** [comment]
Closed in favor of #433

**Pull request closed without merging**
