### PR TITLE
mention JIRA Issue Tracker with link

### PR DESCRIPTION
**Pull request by lazaridiscom**
(please feel free to not merge / completely change. Just mention the JIRA somehow)

### CODE REVIEW

**Comment by arsulegai** [comment]
Hello @lazaridiscom thank you for the PR. Could you please sign-off you commit? (Please refer to the link mentioned in the same CONTRIBUTING.md file that you modified).

BTW, I prefer add the Jira link in a separate line. (form your own sentence) Something like "Jira is used for tracking the feature additions and fixing the bugs. Please see here ... link ...". There is a continuation statement for the current line which breaks with this line. You may also want to point to the document section along to know more details.

**Comment by lazaridiscom** [comment]
The linux-foundation is really a master in "killing energy with redundant processes". Filing the first issue in your project was a small hell. And issues seem to be ignored (e.g. https://jira.hyperledger.org/projects/STL/issues/STL-1692), thus I went on to file a PR.

I'll not sign the (doc only) PR with this archaic procedure (https://developercertificate.org/). You should really change this to the usual one-time CLA (SAP has provided a nice tool).

In any way:

> (please feel free to not merge / completely change. Just mention the JIRA somehow)

Just modify, or close and do the change as you see fit.

All good for me.

**Comment by Etienereum** [comment]
Completely trueOn Feb 18, 2020 3:57 AM, Lazaridis <notifications@github.com> wrote:(please feel free to not merge / completely change. Just mention the JIRA somehow)



You can view, comment on, or merge this pull request online at:
  https://github.com/hyperledger/sawtooth-core/pull/2287

Commit Summary
mention JIRA Issue Tracker with link

File Changes

    M
    CONTRIBUTING.md
    (2)
  

Patch Links:
https://github.com/hyperledger/sawtooth-core/pull/2287.patchhttps://github.com/hyperledger/sawtooth-core/pull/2287.diff

**Comment by vaporos** [comment]
The DCO process is not optional. Closing. Feel free to remedy and re-open.

**Comment by lazaridiscom** [comment]
@vaporos , 

## Problem A

why do you close this, without actually taking the relevant action? The link is missing, and should be added.

## Problem B

Now, do me a favor and use the github UI (like I did for the PR), and lets see if you manage to "follow the mandatory process" and sign-off the commit via the github UI.

## Problem C

Attempt the same via usual clone locally, but without(!) using your real email (see, I simply don't want my email within commits)

I can't express how disappointed I am by all this. Linux foundation  blows organizational things unnecessarily out. I had never(!) ever(!) such a problem within hundred of projects on github.


> The DCO process is not optional. 

This is not something that can be called a "process".

This  is something worth of the term "process": https://cla-assistant.io/

Shred DCO, use github-UI compatible CLA.

.

**Comment by lazaridiscom** [comment]
follow-upQ https://lists.hyperledger.org/g/dci-wg/topic/example_of_non_inclusive/71367024?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,71367024

**Pull request closed without merging**
