### PR TITLE
Update sawtooth-signing imports to use generic signing module

### PR DESCRIPTION
**Pull request by dcmiddle**
Signed-off-by: dcmiddle <dan.middleton@intel.com>

### CODE REVIEW

**Comment by jjason** [comment]
Lint doesn't like you.

**Comment by jjason** [comment]
@peterschwarz I am not a Python-ista, but would it be more Pythonic to, in the `__init__.py` file have:

`from sawtooth_signing import secp256k1_signer as signing`

and then in the other files:

`from sawtooth_signing import signing`

???

**Comment by jjason** [comment]
@dcmiddle Should this be closed???

**Comment by dcmiddle** [comment]
closing in favor of #261

**Pull request closed without merging**
