### PR TITLE
Avoid breaking loop to find handler in go sdk transaction processor

### PR DESCRIPTION
**Pull request by john-jam**

### CODE REVIEW

**Comment by aludvik** [comment]
@john-jam Good catch!

We need to tidy up this PR a little in order to get it merged. In order for this to pass the DCO, all commits need to be signed off `git commit -s ...`. It looks like you have two out of three commits that are not signed off right now. However, it looks like only one of the commits is needed. Our workflow in this case is to do a `git rebase -i upstream/master` and drop all the unneeded commits, keeping only the one signed off commit that fixes the issue. (Rebasing in git: https://git-scm.com/book/id/v2/Git-Branching-Rebasing, Interactive rebasing: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) In the above example, upstream is the Hyperledger fork: `github.com:hyperledger/sawtooth-core.git`

When you have done that, you can check that the rebase was successful by doing `git log` and confirming that you have just the one commit you kept, followed by the head of master.

Details on DCO: https://github.com/probot/dco#how-it-works
Details on Contributing to Sawtooth: https://sawtooth.hyperledger.org/docs/core/nightly/master/community/contributing.html

**Comment by aludvik** [comment]
Also, I noticed that this line also includes a break that should be a continue if you want to fix that while you're at it: https://github.com/hyperledger/sawtooth-core/blob/master/sdk/go/src/sawtooth_sdk/processor/worker.go#L142

**Comment by john-jam** [comment]
Okay I just did it but I'm not able to push on my branch (Your branch and 'origin/go_sdk_bug_fix' have diverged). I don't know why ?

**Comment by john-jam** [comment]
Okay, my bad... I just had to force push

**Comment by grkvlt** [comment]
@john-jam can you rebase this PR against `master` please, so that the tests can run properly? something like `git pull --rebase origin master && git push --force john-jam go_sdk_bug_fix` with appropriate remote names...

**Comment by john-jam** [comment]
Hi @grkvlt, my branch is now rebased against master (hyperledger sawtooth-core with Merge pull request #1532 from boydjohnson/STL-1052.dependencies as last commit) but the jenkins integration continues to fail. I had the same unsuccessful check when I just forked and committed. Please tell me if something is wrong ? Thx

**Comment by aludvik** [comment]
@john-jam sorry for the delay in getting back to this. We have a whitelist of users whose PRs are allowed to build on our CI, which is why your build was failing. I did a one-time manual override of this check for you, so it should build now. Feel free to ping me on https://chat.hyperledger.org/ if I get distracted again (username adamludvik)

**Comment by vaporos** [comment]
The commit message is good, but it would be even better with additional explanation of the bug that it fixes.

https://chris.beams.io/posts/git-commit/

**Comment by john-jam** [comment]
@vaporos @aludvik commit edited & rebased against master :)

**Pull request merged**
