### PR TITLE
Remove PoET From Core

### PR DESCRIPTION
**Pull request by peterschwarz**
This PR removes PoET, its tests and its usage from tests. PoET is being moved to its own repository, [sawtooth-poet](https://github.com/hyperledger/sawtooth-poet).  When the PR to add PoET to that repos is submitted, a comment will be added to this PR.

Additionally, a future PR will add a Jenkins step to test the validator against the PoET consensus engine to help watch for regressions between the two.

### CODE REVIEW

**Comment by peterschwarz** [comment]
PR for the addition of PoET to it's own repository: https://github.com/hyperledger/sawtooth-poet/pull/1

**Comment by boydjohnson** [comment]
@peterschwarz I see the PoET sgx build script but there is a package, `consensus/poet/sgx/sawtooth_poet_sgx` still in the repo after this PR? Should a removal of that package be part of this PR?

**Comment by peterschwarz** [comment]
Rebased on master

**Comment by boydjohnson** [comment]
@peterschwarz This was a problem with my local checkout.

**Comment by peterschwarz** [comment]
Added a commit to remove the reference to poet from the legacy ConsensusFactory

**Comment by Glenrun** [comment]
@peterschwarz so poet-sgx was only removed from this repository, but it continues to be supported by [sawtooth-poet](https://github.com/hyperledger/sawtooth-poet) in latest version, right?

**Comment by peterschwarz** [comment]
That is correct. The code removed by this PR was moved there.

**Pull request merged**
